apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "cloudvmbroker.fullname" . }}-data-config
  labels:
    app.kubernetes.io/name: {{ include "cloudvmbroker.name" . }}
    helm.sh/chart: {{ include "cloudvmbroker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.yaml: |-
    # User-supplied common configuration:
    {{- if .Values.configuration }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration "context" $ ) | nindent 4 }}
    {{- end }}
    # End of common configuration
