platform: linux/amd64

labels:
  type: exec

pipeline:
- name: test-e2e
  image: bash
  commands:
  - export VERSION=$([ -z $CI_COMMIT_TAG ] && echo latest || echo $CI_COMMIT_TAG)-$(sed 's#/#-#g' <<< $CI_SYSTEM_ARCH)
  - export CI_COMMIT_TAG=$([ -z $CI_COMMIT_TAG ] && echo latest || echo $CI_COMMIT_TAG)
  - make test-e2e
  - make coverage
  - curl -s https://codecov.io/bash | bash
  environment:
    KIND_EXPERIMENTAL_PROVIDER: podman
  secrets:
  - codename
  - codecov_token
  - dev_registry
  - drycc_registry
  when:
    event:
    - push
    - tag
    - pull_request
